#!/usr/bin/env bash

# Get the hostname location and command from the platform
getfacts=`which facter`
fqdn=`${getfacts} fqdn --no-external-facts`

# Check the fqdn for locations of Data Centers
if [[ "${fqdn}" =~ '.scflab.' ]]; then
  echo "datacenter=scflab"
elif [[ "${fqdn}" =~ '.slca.' ]]; then
  echo "datacenter=slca"
elif [[ "${fqdn}" =~ '.slcb.' ]]; then
  echo "datacenter=slcb"
elif [[ "${fqdn}" =~ '.phx.' ]]; then
  echo "datacenter=phx"
elif [[ "${fqdn}" =~ '.lvs.' ]]; then
  echo "datacenter=lvs"
elif [[ "${fqdn}" =~ '.lvsuaz.' ]]; then
  echo "datacenter=lvsuaz"
elif [[ "${fqdn}" =~ '.qa.' ]]; then
  echo "datacenter=qa"
elif [[ "${fqdn}" =~ '.chd.' ]]; then
  echo "datacenter=chd"
elif [[ "${fqdn}" =~ '.puppet.' ]]; then
  echo "datacenter=vagrant"
else
  echo "datacenter=unknown"
fi
