source "https://rubygems.org"

  if ENV.key?('PUPPET_VERSION')
    PUPPET_VERSION = "=#{ENV['PUPPET_VERSION']}"
  else
    puppetversion = ['>= 2.7']
  end

  gem 'rake'
  gem 'puppet-lint', '>= 2.1.1'
  gem 'rspec-puppet', '>= 0.1.3'
  gem 'rspec-puppet-facts'
  gem 'puppetlabs_spec_helper', '>= 0.8.2'
  gem 'puppet', puppetversion
  gem 'facter', '>= 1.7.0'
  gem 'bundler'
  gem 'mocha'
  gem 'parallel_tests'
  gem 'rubocop'
  gem 'pry'
  gem 'json_pure'
  gem 'fast_gettext'
  gem 'rainbow'
  gem 'json'
  gem "metadata-json-lint"
  gem 'puppet_facts'
  gem 'puppet-blacksmith'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'rspec_junit_formatter'
  gem 'serverspec'
  gem 'rgen'
  gem 'msgpack'
  gem 'beaker'
  gem 'beaker-rspec'
  gem 'beaker-puppet_install_helper'
  gem "rspec"
