require 'rubygems'
require 'bundler/setup'
require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'
require 'metadata-json-lint/rake_task'

  PuppetLint.configuration.send('relative')
  PuppetLint.configuration.send('disable_80chars')
  PuppetLint.configuration.send('disable_140chars')
  PuppetLint.configuration.send('disable_quoted_booleans')
  PuppetLint.configuration.send('disable_class_inherits_from_params_class')
  PuppetLint.configuration.send('disable_documentation')
  PuppetLint.configuration.send('disable_single_quote_string_with_variables')
  PuppetLint.configuration.ignore_paths = ["spec/**/*.pp", "pkg/**/*.pp"]

  desc "Validate manifests, templates, and ruby files"
    task :validate do
      Dir['manifests/**/*.pp'].each do |manifest|
        sh "puppet parser validate --noop #{manifest}"
      end
      Dir['spec/**/*.rb','lib/**/*.rb'].each do |ruby_file|
        sh "ruby -c #{ruby_file}" unless ruby_file =~ /spec\/fixtures/
      end
      Dir['templates/**/*.erb'].each do |template|
        sh "erb -P -x -T '-' #{template} | ruby -c"
      end
      Dir['manifests/**/*.pp'].each do |manifest|
        sh "puppet-lint \
          --no-140chars-check \
          --with-filename #{manifest}"
      end
      Dir['./metadata.json'].each do |metadata|
        sh "metadata-json-lint --no-strict-dependencies #{metadata}"
      end
  end
